### ISSUE TITLE
rate() raises exception when passing an int

### ISSUE THREAD

**Issue by brantlk** [ampache/python3-ampache#17]
I've got a tool that works with python3-ampache 6.6.7 but stopped working with 6.7.0.

When calling the API.rate() method it started raising an exception:

```
  in my code:
    res = get_connection().rate('song', song_info['id'], rating)
  File "/lib/python3.13/site-packages/ampache.py", line 3014, in rate
    if rating.isdigit():
       ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isdigit'
```

I think that rate() should work when calling with a valid int rather than raising an exception. It gets converted to an int anyways.

**Comment by brantlk** [comment]
Here's the change: https://github.com/ampache/python3-ampache/commit/5387a670ce84947a73ed6b52bf84a6cd06bd6662

**Comment by lachlan-00** [comment]
yeah i've fixed that with https://github.com/ampache/python3-ampache/commit/93589f5966ce92f0491c50c61c74f185ce6f6eff

I'm going to release this today after i finish my doc script.

**Comment by lachlan-00** [comment]
https://pypi.org/project/ampache/

6.8.0 out now, i've been running through all the api from v3-6 and will be releasing a new ampache with fixes for all the things i found as well next week

**Comment by brantlk** [comment]
I upgraded to 6.8.0 and it's working for me.
